title: SwinUNETR3D
project_dir: '../../alveolar_canal/results'
seed: 42

experiment:
  name: Segmentation

data_loader:
  dataset: ../../alveolar_canal/dataset_for_public
  training_set: generated
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 3
  labels:
    BACKGROUND: 0
    INSIDE: 1
  num_workers: 4
  patch_shape:
  - 128
  - 128
  - 128
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 0
  volumes_max: 2100
  volumes_min: 0

model:
  name: SwinUNETR

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: Adam

trainer:
  reload: False # True
  checkpoint: ''
  do_train: True
  do_test: False
  do_inference: False
  epochs: 200
  name: SwinUNETR
