title: DeepLabV3-ResNet152
project_dir: 'results'
seed: 42

experiment:
  name: Segmentation

data_loader:
  dataset: ../../alveolar_canal/dataset_for_public
  training_set: generated
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 36
  labels:
    BACKGROUND: 0
    INSIDE: 1
  num_workers: 4
  patch_shape:
  - 120
  - 120
  - 120
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 0
  volumes_max: 2100
  volumes_min: 0

model:
  name: DeepLabV3-ResNet152

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: Adam

trainer:
  reload: True
  checkpoint: 'weights/DeepLabV3-ResNet152_1270C19D1C/checkpoints/best.pth'
  do_train: False
  do_test: False
  do_inference: True
  epochs: 200
  name: DeepLabV3-ResNet152
